### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by SangbumChoi** [SangbumChoi/Project1_SWZZAZZ#44]
when we use pyinstaller main_gui.py it successfully generates the file in the dist folder. However there is an import error

**Comment by SangbumChoi** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/34004152/74805557-c3610700-5326-11ea-9c15-2bc83c9e72be.png">

**Comment by SangbumChoi** [comment]
The website that i am looking at on
https://github.com/pytorch/pytorch/issues/29035
https://github.com/pytorch/pytorch/pull/29623
https://github.com/pawamoy/mkdocstrings/issues/40
https://www.google.com/search?q=torchvision+pyinstaller+error&rlz=1C1SQJL_enKR881KR881&oq=t&aqs=chrome.1.69i60j69i59l3j69i60l4.3083j0j7&sourceid=chrome&ie=UTF-8
https://www.google.com/search?rlz=1C1SQJL_enKR881KR881&sxsrf=ACYBGNR4Tj8BTKE7FbDwnWnddHF1LK6Ltg%3A1582090076628&ei=XMdMXsXyJZDAoASHwLbYAw&q=torchvision+ops+poolers.py+could+not+get+source+code&oq=torchvision+ops+poolers.py+could+not+get+source+code&gs_l=psy-ab.3...2722.10465..11076...0.0..0.189.3872.0j28......0....1..gws-wiz.......35i39j33i160j33i21.61b2ELgvBSM&ved=0ahUKEwjFkJTo8NznAhUQIIgKHQegDTsQ4dUDCAs&uact=5

**Comment by SangbumChoi** [comment]
C:\Users\daniel\PycharmProjects\Project1\dist\main_gui>main_gui.exe
Traceback (most recent call last):
  File "site-packages\torch\_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_gui.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "VideoPlayer\VideoList.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Library\detectron2\demo\open_demo.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\utils\predictor.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\data\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\data\build.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\structures\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\structures\boxes.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\layers\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "detectron2\layers\nms.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\ops\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\daniel\Anaconda3\envs\Project1\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torchvision\ops\poolers.py", line 43, in <module>
  File "site-packages\torch\jit\__init__.py", line 1274, in script
  File "site-packages\torch\jit\__init__.py", line 1114, in _compile_and_register_class
  File "site-packages\torch\jit\frontend.py", line 150, in get_jit_class_def
  File "site-packages\torch\jit\frontend.py", line 150, in <listcomp>
  File "site-packages\torch\jit\frontend.py", line 162, in get_jit_def
  File "site-packages\torch\_utils_internal.py", line 50, in get_source_lines_and_file
OSError: Can't get source for site-packages\torchvision\ops\poolers.py. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
[7640] Failed to execute script main_gui

**Comment by kdh0324** [comment]
![KakaoTalk_20200505_033824088](https://user-images.githubusercontent.com/55946729/81002368-10fc0300-8e84-11ea-8fb2-6f9eee372c48.png)

**Comment by kdh0324** [comment]
```
272 INFO: PyInstaller: 3.6
272 INFO: Python: 3.7.5 (conda)
274 INFO: Platform: Windows-10-10.0.18362-SP0
276 INFO: wrote D:\Desktop\github\Team_Island_SW\main_gui.spec
291 INFO: UPX is not available.
299 INFO: Extending PYTHONPATH with paths
['D:\\Desktop\\github\\Team_Island_SW', 'D:\\Desktop\\github\\Team_Island_SW']
299 INFO: checking Analysis
2348 INFO: checking PYZ
2811 INFO: checking PKG
3773 INFO: Building because D:\Desktop\github\Team_Island_SW\build\main_gui\main_gui.exe.manifest changed
3773 INFO: Building PKG (CArchive) PKG-00.pkg
Cannot find ('torch\include\ATen\core\EnableNamedTensor.h', 'C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\torch\include\ATen\core\EnableNamedTensor.h', 1, 'x')
Traceback (most recent call last):
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\Scripts\pyinstaller-script.py", line 10, in <module>
    sys.exit(run())
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "D:\Desktop\github\Team_Island_SW\main_gui.spec", line 33, in <module>
    console=True )
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\api.py", line 436, in __init__
    upx_exclude=self.upx_exclude
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\api.py", line 199, in __init__
    self.__postinit__()
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\building\api.py", line 284, in assemble
    pylib_name=pylib_name)
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\archive\writers.py", line 336, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\archive\writers.py", line 63, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\archive\writers.py", line 88, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\archive\writers.py", line 383, in add
    fh = open(pathnm, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kimda\\Anaconda3\\envs\\TeamIsland\\lib\\site-packages\\torch\\include\\ATen\\core\\EnableNamedTensor.h'
```

**Comment by kdh0324** [comment]
위 문제는 아래 사이트를 참고하여
https://stackoverflow.com/questions/44163457/pyinstaller-filenotfounderror-errno-2-no-such-file-or-directory/48505742

```
added_files = [
         ( './core', 'core' )
         ]
```
를 추가하여 해결하였습니다.

**Comment by kdh0324** [comment]
`WARNING: file already exists but should not: C:\Users\kimda\AppData\Local\Temp\_MEl113042\torch\_C.cp-37.win_amd64.pyd`
 exe 실행 시 에러 발생

**Comment by kdh0324** [comment]
> `WARNING: file already exists but should not: C:\Users\kimda\AppData\Local\Temp\_MEl113042\torch\_C.cp-37.win_amd64.pyd`
> exe 실행 시 에러 발생

https://github.com/pyinstaller/pyinstaller/issues/4561

**Comment by kdh0324** [comment]
> > `WARNING: file already exists but should not: C:\Users\kimda\AppData\Local\Temp\_MEl113042\torch\_C.cp-37.win_amd64.pyd`
> > exe 실행 시 에러 발생
> 
> [pyinstaller/pyinstaller#4561](https://github.com/pyinstaller/pyinstaller/issues/4561)
> @SangbumChoi

_C.cp-37.win_amd64.pyd 파일은 다음과 같습니다.

```
MZ?         ?       @                                      ? ???L?This program cannot be run in DOS mode.

$       뤽V싿???原???희???희???흩???힌???힐???흩?????흰???흰??舟???흰??ich?8?        PE  d? 욦^        ? "           p                                p          `                                   P&  T   ?  d    P  ?    @  ?           `      !                             ?  ?               ?                           .text   S                          `.rdata  ?                        @  @.data   8   0                     @  ?pdata  ?   @      "              @  @.rsrc   ?    P      $              @  @.reloc       `      &              @  B                                                                                                                                                                                                                                                                        儆儆儆ff?     H;
?  ?H좋f泰?稷H좼褥  儆?껋(끨t9껉t(껉t껡t
?   H꺞(췄?  ??  뗌H꺞(홇뗊H꺞(?   M끐빦H꺞(?  H?$H뎥$H?$ AVH껋 H뗳L뗲3  꽵u3잰?   ?  듰뉲$@@??%   t
?   ?	  ?%     腕  꽵tO?
  ?  ?  H?5  H?&  瓮  끐u)?  꽵t H?  H??  ?  ??     @2듚?  @?꿧?  H뗗H? t$H뗁?  꽵tH?H뗅?
  L떾?   I뗈??  ?   H?$0H땤$8H?$HH꺞 A^촌H?$H뎥$WH껋 @딋??  3??3잼Z?~  ?  @딒뉲$8?$  t
?   燎  ?  ?  ?	  ??  蜈  @듡?  3?듟?  꽵빩떸H?$0H땤$@H꺞 _홆떹H뎊 L?덽H덳VWAVH껋@I뗱뗻L뗲끨u9?  3잰?   뛄껟w*擁   뗗덬$0끐꼵   L떾뗖I뗈蘊?뗗덬$0끐tvL떾뗖I뗈?  뗗덬$0?u+끐u'L떾3?뗈?  L떾3?뗈??L떾3?뗈?   ?t?u*L떾뗖I뗈??뗗덬$0끐tL떾뗖I뗈?   뗗덬$0?3?\$0떸H?$xH꺞@A^_^촌儆H?$H뎛$H뎥$WH껋 H?)  I뗹뗳H뗩H끱u뛅?H뗅?  L떿뗕H뗇??$0H땗$8H땤$@H꺞 _홆?$H뎥$WH껋 I뗹뗚H뗲껡u?  L떿뗒H뗈H?$0H땤$8H꺞 _??儆?SH껋 H뗙3?_  H뗅N  X  H뗁? 픆꺞 [H%L  H덹$H껋8?   屋	  끐t?   ?H??  沃   H딡$8H??  H뛆$8H꺚H?^  H??  H?(  H딡$@H?,  ?  	 의?     ?     ?   Hk? H??  H?   ?   Hk? H?~  H덹 ?   Hk?H?a  H덹 H??  ? H꺞8촌儆@SVWH껋@H뗙7  H떝?   3E3픆뛗$`H뗈%  H끐t9H긠$8 H뛎$hH딻$`L뗁H덹$0L떾H뛎$pH덹$(3??$ ?  ?|켋꺞@_^[촌儆H?$ UH뗭H껋 H??  H?㈜-?  H;홻tH긡 H뛏?  H딢H덭?  떲H1E?  떲H뛏 H1E?  딢 H뛏H줘 H3E H3EH3핰?  H#핰?㈜-?  H;홆D핰?E  H?$HH討H?.  H꺞 ]홆껋(껡uH?w   uo
  ?   H꺞(촌H??  H%^
  儆H??  ?  H??  홆??  홆껋(了H?畏H?H꺞(촌H껋(?  끐t!eH?%0   H딫?H;?3쟈H?x  u?픆꺞(챨疑儆?껋(?  끐t?  ?堯  뗁?  끐t2잼?  ?H꺞(홆껋(3A  꽵빥H꺞(촌儆H껋(?  꽵u2잼?  꽵u瑤  膺?H꺞(홆껋(堯  畏  ?H꺞(촌儆H?$H뎛$H뎥$WH껋 I뗺I뗱뗚H뗩?  끐u껢uH뗉?  L떾3?뗇?딻$X딯$PH?$0H땗$8H땤$@H꺞 _?  儆?껋(?  끐tH?l  H꺞(?  ?  끐u?  H꺞(홆껋(3=  H꺞(?  @SH껋 ?_  끟?   D횊O  嶢  ?  꽵u2잼?   꽵u	3?  凝듑H꺞 [촌儆H?$UH뗭H껋@=?   뗙뀵   껠눓   ?  끐t-끱u)H??  ?  끐t2잰   H??  ?  끐tg揖H??  ?   떷꺺?+?꺢H談H3헔덭?덭?E?덭倧M?\  H덭?덭?E?덭倧
T  ?M?P  ?
X  ?  ?H?$PH꺞@]첫   療   儆H껋L떶퇝Z  f9
?uyHc@?H?恰H??PE  u_?  f9AuTL+?텮H뛓H?텮H?L???$I;?딭L;햞
딟핶;픯H꺜(隱3?끨u2잼긼$ }2잼
??2잼2픆꺞촌儆@SH껋 듲?  3?픱꾗uH?N  H꺞 [?SH껋 =s   듲t꾋u듚?  듚?  ?H꺞 [촌H?]  횄%I   홆?$UH뜫$@?H곸?  뗙?   獒  끐t뗅??   訛3?뛏?먁  ?  H뛏??  H떇?   H뜒?  H뗅E3??  H끐t<H긠$8 H뜊?  H땿?  L뗁H덹$0L떸H뜊?  H덹$(H뛏?덹$ 3??  H땯?  H뛎$PH뎲?   3?뛿?  A툡   H꺚H뎲?   燎  H땯?  H덬$`?$P  @?$T   ?  껟H뛆$PH덬$@H뛇?붌H덬$H3?&  H뛎$@  끐u꾗u뛊瓦?H떆$?  H겺?  ]촌??$H뎥$WH껋 H??  H??  ?H?H?t
H뗉?   ?꺝H;???$0H땤$8H꺞 _촌??$H뎥$WH껋 H?f	  H?_	  ?H?H?t
H뗉?   ?꺝H;???$0H땤$8H꺞 _촌?%1  ??$H뎛$VWAVH껋36     3의&     줔뗂D뗎곿cAMD괁enti뗫E3??uthD떸?뗱?곿ntelA곾GenuA뛅3?괁ineI줕?$E?\$뗲덹$뗹뎆$uPH??  %?=? t(=` t!=p t곶?껟 w$H?     HＡsD??  A꺢D??  ?D?~  낇u곭 ?? ` rA꺢D?a  ?   D;?'3?쥒$D뗛?$덹$뎆$뷩	sA꺢D?0  뷸sn?     ?
     뷸sT뷸sN3??줴 H?뎆$0H딡$0$<u2??  꺢??     ??  A稚 t꺢 ??     ??  H?$83픆땗$@H꺞A^_^촌儆?   촌???  빥쳇  儆儆?%?  %?  %?  %?  %?  %?  %?  %?  %?  %?  %?  %?  ?촌3읔?%?  儆儆儆儆儆儆儆?f?     羨儆儆儆儆儆儆儆儆儆?f?     M3泛%?  ?꺥意I꺥膺I꺥飮I꺥乙I꺥恩儆儆儆륤떸H꺺끐?H?$dL?$?   ?<?#L떶<?L떷<?M떶<?M떷<?M3픋3??玧儆儆儆ffffff?     ?%I  儆儆儆 稷@UH껋 H뗪둓@H꺞 ]???UH껋 H뗪屋?둓8H꺞 ]???UH껋0H뗪H??H덹$(뎆$ L??L딢p딼hH딲`往?륣꺞0]촌@UH뗪H?3?8  ?붆떶]촌                                                                                                                                                                             4(      H(      b(      v(      ?      ?      ?      ?      ?      )      $)      :)      T)      p)      ?              ?      ?      ?              ?      *      *      (*      B*      d*      *      ?               (              ?        `    ?                                                                                    P0    ?                욦^    
   @  ?  ?      ?                                                                                       0                    ?     !                                                                                   0    !            !            GCTL      .text$mn       ?   .text$mn$00 ?  ?   .text$x     ?   .idata$5    ?      .00cfg  !     .CRT$XCA     !     .CRT$XCZ    (!     .CRT$XIA    0!     .CRT$XIZ    8!     .CRT$XPA    @!     .CRT$XPZ    H!     .CRT$XTA    P!     .CRT$XTZ    `!  8  .rdata  ?  @  .rdata$zzzdbg   ?     .rtc$IAA    ?     .rtc$IZZ    ?     .rtc$TAA    ?     .rtc$TZZ    ?  X  .xdata  P&  T   .edata  ?  P   .idata$2    ?     .idata$3    '  ?   .idata$4     (  ?  .idata$6     0  @   .data   @0  ?  .bss     @  ?  .pdata   P  `   .rsrc$01    `P  ?   .rsrc$02                                        t	 d 4 2逝     ?  4  ?       2P d 4 2p?     ?  ?  ?      	 4 r?p`?     Y         RP	 	b   rp`0
 
4	 
2P	 "  ?     ?  r  ;  r   P   20
 
4
 
rP d T 4 2p B   4? ? P   d 4 2p T 4 ?p`                               ?           x&  |&  &  ?  ?    _C.cp37-win_amd64.pyd PyInit__C   ?          "(  ?  '          ?      ?          ?     ?          ?  ?                      4(      H(      b(      v(      ?      ?      ?      ?      ?      )      $)      :)      T)      p)      ?              ?      ?      ?              ?      *      *      (*      B*      d*      *      ?               (              : ?initModule@@YAPEAU_object@@XZ  torch_python.dll  ?RtlCaptureContext ?RtlLookupFunctionEntry  ?RtlVirtualUnwind  ?UnhandledExceptionFilter  sSetUnhandledExceptionFilter GetCurrentProcess ?TerminateProcess  ?IsProcessorFeaturePresent IQueryPerformanceCounter GetCurrentProcessId  GetCurrentThreadId  ?GetSystemTimeAsFileTime  DisableThreadLibraryCalls gInitializeSListHead }IsDebuggerPresent KERNEL32.dll   __C_specific_handler  % __std_type_info_destroy_list  > memset  VCRUNTIME140.dll  6 _initterm 7 _initterm_e ? _seh_filter_dll  _configure_narrow_argv  3 _initialize_narrow_environment  4 _initialize_onexit_table  " _execute_onexit_table  _cexit  api-ms-win-crt-runtime-l1-1-0.dll                                                                                                                                                                                                                                                                                                                             ? ??2㈜-?            /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1  ?  4  ?  ?  ?  ?  ?  ?  $  0%  $    X%    p  ?  p  ?  &  ?  ?  ?  ?  ?  ?  ?  )  ?  ,  ?  ?  ?  ?  ?  (  C  ?  D  }  ?    ?  ?  ?  ?  ?  ?  ?  ?  ?  	  ?    m  ?  p  ?  ?  ?  ?  ?  ?  ?  ?     ?  ?  ?  y  ?  |  ?  ?  ?  ?  ?  ?  &   &  (  r  &  t  ?  &  ?  ?   &      8&  0  Y  @&  `  ?  D&  ?  ?  H&  ?  ?  L&  ?  ?  (%  ?    (%    ;  %  ;  S  ?                                                                                    0                 	  H   `P  ?                   <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns='urn:schemas-microsoft-com:asm.v1' manifestVersion='1.0'>
</assembly>
                                                                                                                                                                                                                                                                                       ? ??죋죖⊂??줽쥅쥏?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
```

**Comment by SangbumChoi** [comment]
제가 발생했던 오류의 경우 poolers.py인데 이것과 지금 올려주신 코멘트가 일치하는지 우선 확인해보겠는데 연관성은 잘모르겠습니다. 이와관해서 미팅해보시죠

**Comment by SangbumChoi** [comment]
> 위 문제는 아래 사이트를 참고하여
> https://stackoverflow.com/questions/44163457/pyinstaller-filenotfounderror-errno-2-no-such-file-or-directory/48505742
> 
> ```
> added_files = [
>          ( './core', 'core' )
>          ]
> ```
> 
> 를 추가하여 해결하였습니다.

exe 파일자체가 안만들어지는 것을 만들어지는 것으로 치환함 still problem

**Comment by kdh0324** [comment]
![KakaoTalk_20200505_221351163](https://user-images.githubusercontent.com/55946729/81070133-ce870480-8f1d-11ea-9c29-551527470331.png)

**Comment by kdh0324** [comment]
When debugging by spec file, there are errors like these.

```
Traceback (most recent call last):
  File "site-packages\torch\_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_gui.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "VideoPlayer\VideoList.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Library\detectron2\demo\open_demo.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\__init__.py", line 367, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\distributions\__init__.py", line 112, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\kimda\Anaconda3\envs\TeamIsland\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\distributions\von_mises.py", line 54, in <module>
  File "site-packages\torch\jit\__init__.py", line 1287, in script
  File "site-packages\torch\jit\frontend.py", line 164, in get_jit_def
  File "site-packages\torch\_utils_internal.py", line 53, in get_source_lines_and_file
OSError: Can't get source for <function _rejection_sample at 0x0000000006BD1048>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code
[3032] Failed to execute script main_gui
```

**Comment by SangbumChoi** [comment]
![image](https://user-images.githubusercontent.com/34004152/81094684-d4411200-8f3e-11ea-87d7-6e466484f5de.png)
새로운 tf version 설치시 유사하고 등장하는 항목

**Comment by SangbumChoi** [comment]
일단 희망적 + 불행한 사항 library들을 모두 주석처리하고 
pyinstaller main_gui.py --log-level DEBUG --exclude-module=torch --exclude-module=torchvision
이걸로 pyinstaller를 돌리면 실행파일이 돌아가긴 함

**Comment by SangbumChoi** [comment]
onefile로 만들어도 생성가능

**Comment by SangbumChoi** [comment]
현재 원인 exclude인지 주석처리인지 확인중

**Comment by kdh0324** [comment]
```
  File "site-packages\torch\distributions\von_mises.py", line 54, in <module>
  File "site-packages\torch\jit\__init__.py", line 1287, in script
  File "site-packages\torch\jit\frontend.py", line 164, in get_jit_def
  File "site-packages\torch\_utils_internal.py", line 53, in get_source_lines_and_file
OSError: Can't get source for <function _rejection_sample at 0x0000000007DC1048>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code
```

위 에러를 분석한 결과,

```
@torch.jit.script
def _rejection_sample(loc, concentration, proposal_r, x):
    done = torch.zeros(x.shape, dtype=torch.bool, device=loc.device)
    while not done.all():
        u = torch.rand((3,) + x.shape, dtype=loc.dtype, device=loc.device)
        u1, u2, u3 = u.unbind()
        z = torch.cos(math.pi * u1)
        f = (1 + proposal_r * z) / (proposal_r + z)
        c = concentration * (proposal_r - f)
        accept = ((c * (2 - c) - u2) > 0) | ((c / u2).log() + 1 - c >= 0)
        if accept.any():
            x = torch.where(accept, (u3 - 0.5).sign() * f.acos(), x)
            done = done | accept
    return (x + math.pi + loc) % (2 * math.pi) - math.pi
```

torch.von_mises._rejection_sample 함수와 데코레이터 사이에 발생하는 에러로 추정됨.
위 torch.jit.script를 계속 따라가 _rejection_sample이 사용되는 함수를 찾아본 결과, 아래와 같은 코드가 발견됨.

```
def get_source_lines_and_file(obj, error_msg=None):
    """
    Wrapper around inspect.getsourcelines and inspect.getsourcefile.

    Returns: (sourcelines, file_lino, filename)
    """
    filename = None  # in case getsourcefile throws
    try:
        filename = inspect.getsourcefile(obj)
        sourcelines, file_lineno = inspect.getsourcelines(obj)
    except OSError as e:
        msg = ("Can't get source for {}. TorchScript requires source access in "
               "order to carry out compilation, make sure original .py files are "
               "available. Original error: {}".format(obj, e))
        if error_msg:
            msg += '\n' + error_msg
        raise OSError(msg)

    return sourcelines, file_lineno, filename
```

_rejection_sample함수가 obj로 들어가는 것으로 보이며 _rejection_sample의 return 값은 단순히 실수로 추정되므로 getsourcefile(obj)의 구문에서 에러가 나는 것으로 보임
